#!/bin/sh
# 
# 1999-2010 Nico Schottelius (nico-nsbin at schottelius.org)
# 
# This file is part of nsbin.
#
# nsbin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# nsbin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with nsbin. If not, see <http://www.gnu.org/licenses/>.
#
# Date: 1999-04-02
#
# Move blender output files to your extension
#

if [ -z $1 ]
     then echo "Please choose extension"
          echo "Usage: $0 <extension>"
else
     for i in [0-9][0-9][0-9][0-9]
     do mv $i $i.$1
     done
fi
