#!/bin/bash
#
# Pau Oliva Fora - pof (a) eslack (.) org
#
# Macbook Air 4,2 power management script 
# copy to /etc/pm/power.d/99_macbookair and chmod 755
#

if [ $# -ne 1 ]; then
    echo "$0 brightness (0-15)"
    exit 1
fi

level=$1

# lower brightness (value from 1 to 15)
echo $level > /sys/devices/pci0000:00/0000:00:02.0/backlight/acpi_video0/brightness
