#!/bin/sh
# show all installed figlet fonts
#

set -e

text=${1:-cdist}

#cd /usr/figle*/share/figlet/
cd /usr/share/figlet
cd /usr/share/figlet/fonts/
#for a in *.flf; do BLA=${a%.flf}; echo $BLA; echo hallo | figlet -f $BLA; done
#for a in *.flf; do BLA=${a%.flf}; echo $BLA; echo CM Bofs | figlet -f $BLA; done
#for a in *.flf; do BLA=${a%.flf}; echo $BLA ; echo $BLA | figlet -f $BLA; done
for a in *.flf; do BLA=${a%.flf}; echo $BLA ; echo $text | figlet -f $BLA; done
