#!/bin/sh

#file=`ls -l $1 | egrep '^d' | awk ' {print $9 }'`
#if [ -z file ]; then echo $1;fi

# echo gerade : $1
# file : $file

if [ -d "$1" ]
  then 
  echo "dir : $1"
  chown root.wheel $1 -R
  chmod g+rx $1
  chmod g+r $1 -R
fi
