#!/bin/sh
#
# Nico Schottelius <nico@schottelius.(net|org)>
# Date: June 2003
# Last Modified: 13 Mar 2004
# 
# generate mutt compatibel mailboxe entries
# usage: generate_mutt_mailboxes > ~/.mutt/mailboxes
# (and 'source ~/.mutt/mailboxes' in .muttrc)
#

#firstfile=~/.mutt/preferred_mailboxes

echo 'set folder="~/Maildir"'

if [ -f ~/.mutt/important_mailboxes ]; then
   cat ~/.mutt/important_mailboxes
fi

find ~/Maildir/ -type d -name new | \
   sed -e "s,$HOME/Maildir/,mailboxes +,g"      \
       -e 's,new$,,g'                           \
       -e s'/mailboxes +postponed\///g'         \
       -e 's/mailboxes +$//g' | \
   grep -v '^$' 
