#!/bin/sh
#
# Nico Schottelius <nico@schottelius.(net|org)>
# Date: Wed Apr 30 14:57:23 CEST 2003
# Last Modified: Thu Jun 17 22:37:58 CEST 2004
#
# nico@flapp:~/bin $ cat ~/.script-template 
# author="Nico Schottelius"
# email="nico@schottelius.(net|org)"
#


TEMPLATE=~/.script-template

if [ $# -lt 1 ]; then
   echo "`basename $0`: new script file(s)"
   exit 1
fi


for _file in $@; do 
   if [ -e "$_file" ]; then
      echo "$_file exists. Will not overwrite it. Or will I ?"
   else
      if [ ! -e "$TEMPLATE" ]; then
         echo "Required Template missing. Aborting."
         exit 1
      else
         . $TEMPLATE
         cat << EOF > "$_file"
#!/bin/sh
#
# $author <$email>
# Date: `date +%d-%h-%Y`
# Last Modified: -
#
EOF
      fi
   fi
done
