#!/bin/sh

SLEEP=$1

if [ -z "$SLEEP" ]; then
   echo "$0 Zeit zum Schlafen"
   exit 1
fi

while true; do
   fetchmail >/dev/null
#   offlineimap
   echo "Mails abgeholt, schlafe nun $SLEEP Sekunde(n)"
   sleep $SLEEP;
done
