#!/bin/sh

# Tue Jul 18 15:13:45 CEST 2017
#securemail
#fetchmail
mbsync -a

# Disabled by Mon Jun 20 10:56:19 CEST 2016 -- using mu now
# notmuch new

# offlineimap
# notmuch new

exit 0

cd ~/Maildir
git add .
git commit --quiet -m "Update from $(hostname) $(date +%F-%H:%M)"
#git fetch --quiet origin
git fetch origin

git merge -m "Merge from VM" origin/from-vm

git push --quiet origin master:from-notebook

notmuch new --quiet

exit 0
