#!/bin/sh

WEBS=/home/server/www/webs
WWW=/home/server/www

for tlds in $WEBS/*/*; do
   mkdir -p $WWW/`basename $tlds`
   cd $WWW/`basename $tlds`;
   for domain in $tlds/*; do
      mkdir -p `basename $domain`
      cd `basename $domain`
      for subdomain in $domain/*; do 
         ln -s $subdomain
      done
   done
done
