#!/bin/sh
#
# Nico Schottelius <nico-linux //@// schottelius.org>
# Date: 13-Mär-2007
# Last Modified: -
# Description: Links files from /usr/packages/$pkg/$dir/* to /usr/local/$dir
#

if [ "$#" -ne 2 ]; then
   echo "$0: package (below /usr/packages/) subdir (like bin, lib or include)"
   exit 1
fi

basedir="$1"
subdir="$2"
destination=/usr/local
ddir="${destination}/${subdir}"

# test for existence, abort if conflicts are there
do_exit=0
for file in "${basedir}/${subdir}"/*; do
   basename=$(basename "$file")
   dest="${ddir}/${basename}"

   if [ -e "${dest}" ]; then
      echo "${dest} already exists, abort"
      do_exit=1
   fi
done

if [ "$do_exit" = 1 ]; then
   exit 1
fi

# link!
for file in "${basedir}/${subdir}"/*; do
   ln -s "$file" "$ddir"
done


