#!/bin/sh
tmp=/tmp/.lls.$$
ls -l $* | tee $tmp
sum=0
anz=0
for i in $(cut $tmp -b 33-41); do
	i=${i##*[^0-9,´ ´]*}
	if [ i ]; then
		sum=$[$sum+$i]
		anz=$[$anz+1]
	fi
done
echo -n "$anz Dateien, "
if [ $sum -ge 1000000 ]; then
	echo -n $[$sum/1000000]
	printf "%.3d," $[($sum % 1000000)/1000]
	printf "%.3d" $[$sum % 1000]
elif [ $sum -ge 1000 ]; then
	echo -n $[$sum/1000]
	printf "%.3d" $[$sum % 1000]
else
	echo -n $sum
fi
echo " Bytes"
rm $tmp
