#!/bin/sh

# i3lock -c fe0000 -d

i3lock -t -i ~/.background.png

exit 0

#~/b/i3lock/i3lock -t -i /home/users/nico/oeffentlich/bilder/linux-tux-bsd/think_linux_kachel.png
# sleep 2
# xset dpms force off

# i3lock -i ~/.background.png --dpms --nofork

# try to start - if it already runs it will just exit
if ! pgrep xscreensaver; then
    xscreensaver -no-splash &
    sleep 1
fi

xscreensaver-command -lock
