#!/bin/sh

# i3lock -c fe0000 -d

#~/b/i3lock/i3lock -t -i /home/users/nico/oeffentlich/bilder/linux-tux-bsd/think_linux_kachel.png
# sleep 2
# xset dpms force off

# i3lock -i ~/.background.png --dpms --nofork

# try to start - if it already runs it will just exit
xscreensaver &

xscreensaver-command -lock
