#!/bin/sh


GOOGLE_URL='http://www.google.ch/search?hl=de&q=linux'
REFERER="$GOOGLE_URL"

# the begin of the string which ends in a whitespace
MS_AD='href=/url?sa=l&q=http://tracking-microsoftch.qualitraffic.de'
MS_AD_SED="`echo $MS_AD | sed 's/\//\\\//g'`"

# only matching lines
SED_1="'/$MS_AD_SED/!d'"

echo $SED_1

exit 1

# seconds to wait between queries
#WAIT="42"
WAIT="23"

# user agent
#AGENT="Mozilla/4.0 (compatible; MSIE 5.5; Windows 98)"
AGENT="Mozilla/4.0 (compatible; MSIE 5.5; Windows 2004)"


#URL='http://www.google.de/url?sa=l&q=http://tracking-microsoftch.qualitraffic.de/105.html%3Freferer%3Dgoogle_select&ai=Bh8poE-IRQs7aH7_sQae16egI1J_tCLz9oJ4B6YeHBtCGAxABGAEoBDgAQMQVSKw5yAEB&num=1'
URL='http://www.google.de/url?q=http://tracking-microsoftch.qualitraffic.de/105.html%3Freferer%3Dgoogle_select&amp;sa=L&amp;ai=Bh8poE-IRQs7aH7_sQae16egI1J_tCLz9oJ4B6YeHBtCGAxABGAEoBDgAQMQVSKw5yAEB&amp;client='

while true; do
   curl -A "$AGENT" -e "$REFERER" "$URL"
   sleep $WAIT
done

