#!/bin/sh
# 
# 2011      Nico Schottelius (nico-nsbin at schottelius.org)
# 
# This file is part of nsbin.
#
# nsbin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# nsbin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with nsbin. If not, see <http://www.gnu.org/licenses/>.
#
#
# Create remote git repo and add origin remote locally
#

host=git.schottelius.org
dir="/home/services/git"

if [ $# -ne 2 ]; then
   echo "$0 name description"
   exit 1
fi

name=$1; shift
desc=$1; shift

remote_dir="$dir/$name"
remote="$host:$remote_dir"

# Create on remote side
ssh "$host" "GIT_DIR=$remote_dir git init"
ssh "$host" "echo $desc > $remote_dir/description"

# Initialise git
git remote add origin "$remote"
git push origin master
