#!/bin/sh
# Nico Schottelius
# 2014-06-08
# Show the plan of the week


if [ "$#" -ne 1 ]; then
    echo "$0 <directory-with-notes>"
    exit 1
fi

dir=$1; shift

start=1
end=7

day=$start

while [ "$day" -le "$end" ]; do
    date="$(date +%F -d "$day days")"
    file="$HOME/privat/persoenlich/notizen/$date"

    if [ -f "$file" ]; then
        echo "$date"
        cat "$file"
    fi
    day=$((day+1))
done
