#!/bin/sh

file=$1
host=home.schottelius.org
dir=public_html/pre-release/
url="http://home.schottelius.org/~nico/pre-release"

[ -z "$file" ] && exit 1

scp "$file" "${host}:$dir"
ssh $host "chmod a+r $dir/$file"

echo "Pre-released ${url}/${file}"
