#!/bin/sh

#file=`ls -l $1 | egrep '^d' | awk ' {print $9 }'`
#if [ -z file ]; then echo $1;fi

# echo gerade : $1
# file : $file

if [ -d "$1" ]
  then 
  echo "dir : $1"
  chmod u=rwx,g=rx,o-rwx $1
elif [ -x "$1" ];then
   echo "exe: $1"
   chmod u=rwx,g=rx,o-rwx $1
else
   echo "file: $1"
   chmod g=r,o-rwx $1
fi
