#!/bin/sh
# Nico Schottelius (c) 2001
# nico-linux at schottelius dot org
# make secure connections to your mail servers
# used at conferences / congresses / meetings
#

POP3=110
POP3S=995
IMAP=143
IMAPS=993
SMTP=25

# our secured host
HOST="bruehe.schottelius.org"
HOST="217.14.64.75"
HOST="creme.schottelius.org"
HOST="213.146.113.242"
HOST="nico@62.65.138.78"
HOST="home.schottelius.org"
HOST="nico@77.109.138.222"

if [ $# -ge 1 ]; then
    HOST=$1; shift
fi

ssh -T -f -C -N \
    -L2323:mx3.schottelius.org:$IMAPS   \
    -L4241:mx3.schottelius.org:$SMTP    \
    -L2324:imap.googlemail.com:$IMAPS   \
    -L2325:mail.zhaw.ch:$IMAPS          \
    -R :4242:localhost:22 \
    -D 12345                            \
    "$HOST" "$@"

# Fernzugriff
# ssh -T -f -C -N -R4242:localhost:22 "$HOST"

#ssh -T -f -C -N -L2342:mx2.schottelius.org:$SMTP 62.65.138.66
#ssh -T -f -C -N -L4242:imaps.schottelius.org:$IMAPS "$HOST"
#ssh -T -f -C -N -L2323:ddba020.netstream.ch:$POP3S "$HOST"
#ssh -T -f -C -N -L2342:ddba020.netstream.ch:$IMAP "$HOST"
#ssh -T -f -C -N -L2323:proxy001.exchange.netvs.ch:$IMAP "$HOST"
#ssh -T -f -C -N -L4223:ddba020.netstream.ch:$POP3S "$HOST"

#ssh -T -f -C -N -L2323:smtp.syhosting.ch:$IMAPS "$HOST"
#ssh -T -f -C -N -L2342:smtp.syhosting.ch:$POP3S "$HOST"
#ssh -T -f -C -N -L4242:home.schottelius.org:$IMAP "$HOST"

#ssh -T -f -C -N -L4242:mail.schottelius.org:$POP3 "$HOST"
#ssh -T -f -C -N -L2323:mail.schottelius.org:25 mail.schottelius.org
#ssh -T -f -C -N -L2323:mail.folz.de:110 "$HOST"
