#!/bin/sh

# Restore layouts
i3-msg 'workspace 1; append_layout ~/.i3/workspace-1.json'
i3-msg 'workspace 2; append_layout ~/.i3/workspace-2.json'


# Start programs afterwards and watch matching
chromium &
# slack &
#firefox &
#choqok  &

ssh-add </dev/null && mainemacs &
