#!/bin/sh

start=$(date)

~nico/bin/backup-marker

rsync -av --delete --progress 	\
	--exclude '/proc/*' 	\
	--exclude '/tmp/*' 	\
	--exclude '/sys/*' 	\
	--exclude '/dev/*' 	\
	--exclude '/home/users/nico/.bitcoin/blocks/' 	\
	--exclude '/home/services/usbhd' 	\
	"$@" 			\
	/ root@loch:/home/services/backup/bento-manuell
	#/ root@zuhause.schottelius.org:/home/services/backup/bento-manuell
	#/ root@zuhause.schottelius.org:/home/services/backup/bento-manuell
end=$(date)

echo $start
echo $end
