#!/bin/sh -e

################################################################################
# standard vars stolen from cconf
__pwd="$(pwd -P)"
__mydir="${0%/*}"; __abs_mydir="$(cd "$__mydir" && pwd -P)"
__myname=${0##*/}; __abs_myname="$__abs_mydir/$__myname"

if [ $# -ne 2 ]; then
    echo "$0: src dst"
    exit 1
fi

from=$1; shift
dst=$1; shift

case $from in
    loch)
        src=root@loch:/home/services/backup/notebook-manuell/home/users/nico/
    ;;
esac


sshdir=$(cd "$__abs_mydir/../.ssh" && pwd -P)
sshkey=$sshdir/id_rsa
sshconfig=$sshdir/config

d1=$(date)
set -x
#rsync -avS -e "ssh -i $sshkey -F $sshconfig" --delete "$src" "$dst"
rsync -avS --delete "$src" "$dst"
echo $d1
date
