#!/bin/sh

notmuch tag +ungleich +ticket from:redmine@ungleich.ch

notmuch tag +ungleich from:@ungleich.ch or to:@ungleich.ch
notmuch tag +mitarbeiter from:tobias.kiefer@ungleich.ch or from:david.huerlimann@ungleich.ch or from:fiala@mfiala.net
notmuch tag +ungleich +monitoring from:monitor@ungleich.ch

notmuch tag +p.c.systems from:@pcsystems.de or to:@pcsystems.de

notmuch tag +magrathea from:@magrathea.eu or to:@magrathea.eu 
notmuch tag +magrathea from:@magrathea.de or to:@magrathea.de  
notmuch tag +kunde tag:magrathea

notmuch tag +local.ch from:@local.ch or from:"Philipp Keller"

notmuch tag +ethz from:@inf.ethz.ch or to:@inf.ethz.ch
notmuch tag +ethz from:@ethz.ch or to:@ethz.ch

notmuch tag +hsz-t from:nico-hsz-t@schottelius.org or to:nico-hsz-t@schottelius.org

notmuch tag +agilentia from:@agilentia.ch or to:@agilentia.ch     
notmuch tag +kunde tag:agilentia


notmuch tag +panter +system -inbox to:system@panter.ch
notmuch tag +panter +system -inbox to:system@panter.ch
notmuch tag +panter +system -inbox to:sumasy@panter.ch
notmuch tag +panter +system -inbox to:root@chatbyphonak.com
notmuch tag +panter +system -inbox from:root@zahnfee.denteo.ch
notmuch tag +panter +referenceimiage from:@referenceimage.com or to:@referenceimage.com or from:monit@ri-staging
notmuch tag +kunde +referenceimage -inbox from:rails@panter.ch to:referenceimage@ungleich.ch
notmuch tag +panter +monit -inbox from:monit@hev-forms-production or from:monit@hev-forms-staging or from:monit@recomy-staging
notmuch tag +panter +srg from:@srgssr.ch or to:@srgssr.ch
notmuch tag +panter +cron -inbox from:root@*.panter.ch or from:root@*.panter.biz or from:root@*.referenceimage.com
notmuch tag +panter +cron +recomy -inbox from:monit@recomy-production
notmuch tag +panter -inbox to:technik+jenkins@panter.ch
notmuch tag +panter +newrelic -inbox from:productupdate@newrelic.com to:nico@panter.ch
notmuch tag +panter from:@panter.ch or to:@panter.ch
notmuch tag +kunde tag:panter

notmuch tag +kunde from:krishna@mailbox.org or to:krishna@mailbox.org

notmuch tag +cron to:root@localhost

notmuch tag +straumann from:@straumann.com

notmuch tag +sts +kunde from:@stssensors.com or to:@stssensors.com
notmuch tag +petspremium +initos +kunde from:@petspremium.de or to:@petspremium.de
notmuch tag +petspremium +initos +kunde from:@initos.com or to:@initos.com

notmuch tag +entwine +jira subject:Entwine-Jira
notmuch tag +entwine +jira +ticket +support -inbox from:servers@entwinemedia.com subject:SUPPORT-
notmuch tag +entwine +maintenance subject:"Uninett Weekly maintenance" 
notmuch tag +entwine from:redmine@ungleich.ch subject:"entwine"
notmuch tag +entwine from:@entwinemedia.com or to:@entwinemedia.com
notmuch tag +entwine +backup -inbox from:root@backup.entwinemedia.com
notmuch tag +entwine +newrelic -inbox from:productupdate@newrelic.com to:nico@entwinemedia.com
notmuch tag +entwine +serverdensity -inbox from:@serverdensity.com or to:@serverdensity.com
notmuch tag +entwine +serverdensity -inbox from:"Server Density" and to:nico@entwinemedia.com
notmuch tag +entwine +newrelic -inbox from:noreply@newrelic.com and to:nico@entwinemedia.com
notmuch tag +entwine +basecamp from:notifications@basecamp.com and to:nico@entwinemedia.com
notmuch tag +entwine +basecamp from:notifications@entwine.basecamphq.com and to:nico@entwinemedia.com
notmuch tag +entwine +newrelic -inbox from:noreply@newrelic.com and to:operations@entwinemedia.com
notmuch tag +kunde tag:entwine

notmuch tag +teralytics from:@teralytics.ch or to:@teralytics.ch
notmuch tag +teralytics from:@teralytics.net or to:@teralytics.net
notmuch tag +teralytics +jira +ticket from:jira@teralyticsag.atlassian.net
notmuch tag +teralytics from:redmine@ungleich.ch subject:"teralytics"
notmuch tag +teralytics +cron -inbox from:internal@teralytics.ch
notmuch tag +teralytics -inbox to:infrastructure@teralytics.ch from:nagios@
notmuch tag +kunde tag:teralytics

notmuch tag +voicerepublic from:@voicerepublic.com or to:@voicerepublic.com
notmuch tag +voicerepublic +system -inbox to:root@kluuu.com
notmuch tag +kunde tag:voicerepublic

notmuch tag +vendor +esag +lenovo from:@esag-shop.ch
notmuch tag +vendor +post from:@post.ch
notmuch tag +vendor +sbb +verkehr to:nico-sbb.ch@schottelius.org
notmuch tag +vendor +postfinance +finanzen from:@postfinance.ch
notmuch tag +finanzen +steuer +zuerich from:nico-steuer-zh@schottelius.org or to:nico-steuer-zh@schottelius.org

notmuch tag +vendor +telephoenix +voip +telefon from:telephoenix.ch
notmuch tag +vendor +axa-winterthur +versicherung +ungleich from:nicola.meier@axa-winterthur.ch or from:alexander.waesch@axa-winterthur.ch
notmuch tag +vendor +post +postbox to:nico-swisspostbox@schottelius.org
notmuch tag +vendor +ch-open from:@ch-open.ch
notmuch tag +vendor +dell from:@dell.com or to:@dell.com     
notmuch tag +vendor +dalco from:@dalco.ch or to:@dalco.ch
notmuch tag +vendor +nexellent +rechenzentrum from:@nexellent.ch or to:@nexellent.ch or from:@rt-1.dmz.ch.nexellent.com
notmuch tag +vendor +init7 from:@init7.net or to:@init7.net
notmuch tag +vendor +acceleris  from:@acceleris.ch
notmuch tag +vendor +partner +stepping-stone from:@stepping-stone.ch or to:@stepping-stone.ch
notmuch tag +vendor +buchhaltung +runmyaccounts from:@runmyaccounts.com or to:@runmyaccounts.com
notmuch tag +vendor +hardware +microspot from:@microspot.ch to:@microspot.ch
notmuch tag +vendor +dns +inwx from:@inwx.de or to:nico-inwxo@schotteli.us
notmuch tag +vendor +sumiswalder +versicherung from:@sumiswalder.ch
notmuch tag +vendor +digitec from:@digitec.ch
notmuch tag +vendor +fairphone to:nico-fairphone.com@schottelius.org
notmuch tag +partner +openclouddays from:matthias.guenter@mentor.ch
notmuch tag +vendor +bhphotovideo nico-bhphotovideo@schottelius.org
notmuch tag +vendor +ebookers to:nico-ebookers.ch@schottelius.org
notmuch tag +vendor +tbgs from:@tbgs.ch
notmuch tag +vendor +misco from:@misco.de 
notmuch tag +vendor +hetzner from:@hetzner.de 
notmuch tag +vendor +asus from:@asus.com or to:nico-asus@schottelius.org
notmuch tag +vendor +freecall24 to:freecall24.ch@ungleich.ch
notmuch tag +vendor +kuehlschrank from:@venova.ch

notmuch tag +vendor +ungleich +odesk from:@odesk.com or to:nico-odesk.com@schottelius.org

notmuch tag +vendor +auktion from:@ricardo.ch


notmuch tag +cron from:"Cron Daemon"

notmuch tag +ccollect subject:"ccollect"
notmuch tag +cdi.st subject:cdi.st

notmuch tag +ccc +schweiz +chaostreff -inbox to:chaostreffs@lists.ccc.de 
notmuch tag +ccc +schweiz -inbox to:chaosliste@chaostreff.ch
notmuch tag +ccc +dresden +c3d2 -inbox to:c3d2@lists.c3d2.de 
notmuch tag +ccc +schweiz +zuerich -inbox to:zuerich@chaostreff.ch or to:zuerich-announce@chaostreff.ch
notmuch tag +ccc from:telmich@schottelius.org or to:telmich@schottelius.org  
notmuch tag +ccc +intern -inbox to:intern@lists.ccc.de or to:intern@ccc.de
notmuch tag +ccc +hannover +leitstelle511 -inbox to:511@hannover.ccc.de
notmuch tag +c3d2 +ccc +dresden -inbox to:nico-ccc-c3d2@schottelius.org

notmuch tag +google to:nico-google.com@schottelius.org
notmuch tag +google to:terzoidterzoid@gmail.com
notmuch tag +google to:nico.schottelius@gmail.com
notmuch tag +twitter from:@twitter.com

notmuch tag +foss +gallery +llgal -inbox to:llgal-users@gna.org
notmuch tag +foss +glusterfs -inbox to:gluster-users@gluster.org
notmuch tag +foss +fosdem +conference from:@fosdem.org or from:Kris.Buytaert@inuits.eu
notmuch tag +foss +archlinux +linux +pacman -inbox to:pacman-dev@archlinux.org
notmuch tag +foss +archlinux +linux +ticket from:bugs@archlinux.org
notmuch tag +foss +lugs +linux -inbox from:reminder@lugs.ch or to:linux@lugs.ch or to:lugs@lugs.ch
notmuch tag +foss +debian +linux -inbox to:community@lists.debian.ch
notmuch tag +foss +coda +filesystem +linux to:codalist@coda.cs.cmu.edu
notmuch tag +foss +puppet +configuration-management -inbox to:puppet-users@googlegroups.com
notmuch tag +foss +ssh -inbox to:openssh-unix-dev@mindrot.org
notmuch tag +foss +cdist to:cdist-owner@l.schottelius.org or to:cdist@l.schottelius.org or to:cdist@noreply.github.com
notmuch tag +foss +cdist +sourceforge -inbox from:noreply@code.cdist.p.re.sf.net
notmuch tag +foss +linux +kernel to:stable@vger.kernel.org or to:stable-commits@vger.kernel.org
notmuch tag +foss +linux +dash +shell -inbox to:dash@vger.kernel.org
notmuch tag +foss +filesystem +kernel -inbox to:codalist@coda.cs.cmu.edu
notmuch tag +foss +security +kernel -inbox to:owl-users@lists.openwall.com or owl-dev@lists.openwall.com or to:owl-council@lists.openwall.com
notmuch tag +foss +security -inbox to:password-store@lists.zx2c4.com
notmuch tag +foss +sourceforge -inbox to:users@lists.repoforge.org
notmuch tag +foss +github +vcs from:@github.com
notmuch tag +foss +python +gpg -inbox to:python-gnupg@googlegroups.com
notmuch tag +foss +nico -inbox to:commits@l.schottelius.org
notmuch tag +foss +llgal +gallery to:llgal-users@gna.org
notmuch tag +foss +hostap +linux +wireless -inbox to:hostap@lists.shmoo.com
notmuch tag +foss +monitoring -inbox to:assimilation@lists.community.tummy.com or to:assim-devel@lists.community.tummy.com

notmuch tag +posix -inbox to:austin-group-l@opengroup.org
notmuch tag +net +swinog to:swinog@swinog.ch or to:swinog@lists.swinog.ch
notmuch tag +net +meetup to:nico-meetup.com@schottelius.org
notmuch tag +net +usenix to:nico-usenix.org@schottelius.org or from:@usenix.org
notmuch tag +net +kakoa from:@kakao.com
notmuch tag +net +idee.ch from:@idee.ch


notmuch tag +familie from:thilo@schottelius.net or from:thilo.schottelius@gmail.com
notmuch tag +sanghee from:verysanghee@gmail.com or to:nico-sanghee@schottelius.org or to:verysanghee@gmail.com
notmuch tag +sanghee from:Sarah.Baebler@gl.ch
notmuch tag +freunde +andrea.stenzel to:nico-fr-andrea@schottelius.org
notmuch tag +freunde +dani from:ammanda1@students.zhaw.ch or to:ammanda1@students.zhaw.ch
notmuch tag +freunde +simone to:simone@glinz.li or from:simone@glinz.li
notmuch tag +freunde +tomas.pospisek from:tpo@sourcepole.ch 
notmuch tag +freunde +andi from:@v-net.ch or to:@v-net.ch
notmuch tag +freunde +jihye to:nico-jihye@schottelius.org or from:monpoussin89@hotmail.com
notmuch tag +freunde +steven from:aerueegg@bluewin.ch or from:steven-nico@armstrong.cc or from:steven.armstrong@inf.ethz.ch or to:nico-steven@schottelius.org or from:steven.armstrong@ungleich.ch
notmuch tag +freunde +simone.glinz from:simone@glinz.li
notmuch tag +freunde +ying from:yoongying_loop@hotmail.com
notmuch tag +freunde +alain from:munen@shogen-dojo.org or from:munen@voicerepublic.com or from:alain.lafon@dispatched.ch or from:munen@dispatched.ch
notmuch tag +freunde +tonnerre from:tonnerre@ngas.ch
notmuch tag +freunde +linda from:hartmannlinda@hotmail.com
notmuch tag +freunde +denis from:d.tehlar@gmx.net or to:d.tehlar@gmx.net
notmuch tag +freunde +xia from:xiaoxia.li@gmx.net or to:xiaoxia.li@gmx.net
notmuch tag +su from:subisous@gmail.com or from:s-joho@swissonline.ch or from:susan.joho@juliusbaer.com


notmuch tag +bildung +teaching +zhaw from:@zhaw.ch or to:@zhaw.ch

notmuch tag +consul +foss -inbox to:consul-tool@googlegroups.com

notmuch tag +jiu-jitsu to:nico-jcu@schottelius.org or to:nico-jiu@schottelius.org
notmuch tag +jiu-jitsu +rheinfelden from:"Oliver Gugel" or to:nico-jiu-rhf@schottelius.org
notmuch tag +jiu-jitsu to:nico-pjjcz@schottelius.org or from:Kfl@kapo.zh.ch or from:andy-san@bluewin.ch
notmuch tag +jiu-jitsu +bern from:alfredo.rauber@bluewin.ch
notmuch tag +jiu-jitsu +denisguelat from:clan.guelat@wanadoo.fr

notmuch tag +sprache +korea to:nico-koreanclass101.com@schottelius.org

notmuch tag +sport +hobby tag:jiu-jitsu

notmuch tag +luchsingen from:huerzele@active.ch

notmuch tag -inbox    folder:postponed/
notmuch tag +outgoing -inbox folder:outgoing/
notmuch tag +outgoing -inbox folder:sent/
notmuch tag +outgoing folder:firmen/ungleich/outgoing/
notmuch tag +outgoing folder:firmen/local.ch/outgoing/
notmuch tag +outgoing folder:firmen/ethz/outgoing/

# notmuch dump > ~/Maildir/notmuch-dump

# Have alot and mutt-kz see the same messages in the inbox
#notmuch tag +killed tag:archive
#notmuch tag +archive tag:killed
# reconfigured alot to use archive, too
