#!/bin/sh
# Nico, some years ago

if [ $# -lt 1 ]; then
    echo "$0 host(s)-to-configure"
    exit 1
fi



ssh -A ungleich@control.place5.ungleich.ch "
    cd ~/.cdist
    git pull -v
    git submodule update --init; " '~/cdist/bin/cdist config -vvp' "$@"
