#!/bin/sh
# convert vfat permissions to normal ones..

if   [ -d "$1" ];then chmod 0700 "$1"
else                  chmod 0600 "$1"
fi

# could also be:

#if   [ -d "$1" ];then chmod og-x "$1"
#else                  chmod a-x "$1"
#fi

