#!/bin/sh
xrandr --output HDMI1 --off
xrandr --output DP1 --off

xrandr --output eDP1 --auto
xrandr --output HDMI1 --auto --rotate normal --above eDP1
xrandr --output DP1 --auto --rotate normal --above eDP1
