#!/bin/sh
# 
# 2010      Nico Schottelius (nico-nsbin at schottelius.org)
# 
# This file is part of nsbin.
#
# nsbin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# nsbin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with nsbin. If not, see <http://www.gnu.org/licenses/>.
#
#
# Order device at ISG
#

#
# Standard variables (stolen from cconf)
#
__pwd="$(pwd -P)"
__mydir="${0%/*}"; __abs_mydir="$(cd "$__mydir" && pwd -P)"
__myname=${0##*/}; __abs_myname="$__abs_mydir/$__myname"


if [ -z "$NETHZ_USERNAME" ]; then
   echo "Error: Set \$NETHZ_USERNAME to your username"
   exit 1
fi

if [ $# -ne 3 ]; then
   cat << eof
$__myname: <machine> <ou> <room>

   Requires NETHZ_USERNAME to be set.

   Example: NETHZ_USERNAME="nicosc" $__myname sgn-foobar-42 sans-lab cab/x/99

eof
   exit 1
fi

machine="$1"; shift
ou="$1"; shift
room="$1"; shift

headerto="support@inf.ethz.ch"
to="support@inf.ethz.ch $from"

sendmail="/usr/sbin/sendmail"
from="${NETHZ_USERNAME}@ethz.ch"

cat << eof | $sendmail -f "$from" $to
To: $headerto
Subject: Installation request for Host $machine

Dear support@inf.ethz.ch,

here is the form data from TWiki.


DNS Hostname:    $machine
Graphics card:   nvidia
HDD Size:        1000
Keyboard Layout: en_us
MAC:             IN DHCP
Model:           Dalco
Name:            Nico Schottelius
NumScreens:      1
OU:              $ou
Office:          cab/e/79
Other Info:      
Phone:           27609
Resolution:      1920x1200
Root:            ISG
eMail Address:   nicosc@ethz.ch
group:           $ou
multiboot:       No
os:              Microsoft Windows 7 Enterprise 64bit
(Workstation)
preserve-win:    No
room:            $room

Cheers,

   $USER

-- 
Send by ${__myname}

eof
