#!/bin/sh

case "$1" in
   on)
      xscreensaver -nosplash &
      ;;
   off)
      killall xscreensaver
      ;;
   lock)
      xscreensaver -nosplash &
      xscreensaver-command -lock &
      ;;
esac
